// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdfpawjitlhyqzwwlzvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZnBhd2ppdGxoeXF6d3dsenZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjY4MzYsImV4cCI6MjA1NTIwMjgzNn0.tmlhohNhAWZ4RcnrchNGkT2c3kyFBUmShYujWAdn-08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);